tweak systemd service and run file

diff --git a/run b/run
--- a/run
+++ b/run
@@ -8,8 +8,10 @@ if [ "$(echo $REDIRECT_OUTPUT | tr [A-Z] [a-z] )" = "true" ]; then
     # redirect stdout/stderr (use when preseeding headless deployments)
     LOGFILE=/var/log/inithooks.log
     touch $LOGFILE; chmod 640 $LOGFILE
-    echo "Redirecting output to $LOGFILE"
-    exec > >(tee $LOGFILE|logger -t inithooks -s 2>/dev/console) 2>&1
+    TTY=$(cat /sys/devices/virtual/tty/tty0/active)
+    [ -z $TTY ] && TTY=console
+    tail -f $LOGFILE > /dev/$TTY &
+    PID="$!"
 fi
 
 exec_scripts() {
@@ -18,8 +20,9 @@ exec_scripts() {
     for SCRIPT in $(find $SCRIPT_DIR -type f -or -type l | sort); do
         [ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
         [ -x $SCRIPT ] || continue
-        echo "# $SCRIPT"
+        echo "# running $SCRIPT"
         $SCRIPT
+        echo "# completed $SCRIPT - exit code $?"
     done
     return 0
 }
@@ -31,5 +34,7 @@ if [ "$(echo $RUN_FIRSTBOOT | tr [A-Z] [a-z] )" = "true" ]; then
     exec_scripts $INITHOOKS_PATH/firstboot.d
 fi
 exec_scripts $INITHOOKS_PATH/everyboot.d
+
+kill -9 $PID
 
 exit 0
